# Generated by Django 3.2.5 on 2022-01-09 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=500, null=True, verbose_name='证明描述')),
                ('photo', models.ImageField(blank=True, upload_to='Award/', verbose_name='证明照片')),
            ],
            options={
                'verbose_name': '证明材料',
                'verbose_name_plural': '证明材料',
            },
        ),
    ]
